sudo: required
services:
  - docker

before_install:
  - docker build -t vikas-kumar56/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vikas-kumar56/react-test npm run test -- --coverage

after_success:
  - docker build -t amolkumar56/multi-client ./client
  - docker build -t amolkumar56/multi-nginx ./nginx
  - docker build -t amolkumar56/multi-server ./server
  - docker build -t amolkumar56/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push amolkumar56/multi-client
  - docker push amolkumar56/multi-nginx
  - docker push amolkumar56/multi-server
  - docker push amolkumar56/multi-worker
